@baseUrl = http://localhost:3000

### health check
GET http://localhost:3000/health

### Register new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "ofek1",
  "email": "ofek1@test.com",
  "password": "123456"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "ofek1@test.com",
  "password": "123456"
}

### Access protected route without token
GET {{baseUrl}}/auth/me

### Access protected route with invalid token
GET {{baseUrl}}/auth/me
Authorization: Bearer invalid.token.here

### Access protected route with valid token
GET {{baseUrl}}/auth/me
Authorization: Bearer <accessToken>


### Refresh access token
POST {{baseUrl}}/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "<refreshToken>"
}

### Logout
POST {{baseUrl}}/auth/logout
Content-Type: application/json

{
  "refreshToken": "<refreshToken>"
}

### Get all users
GET {{baseUrl}}/users
Authorization: Bearer <accessToken>

### Get user by id
GET {{baseUrl}}/users/697cf2a1024c7777b05e9313
Authorization: Bearer <accessToken>

### Update user (self)
PUT {{baseUrl}}/users/697cf2a1024c7777b05e9313
Authorization: Bearer <accessToken>
Content-Type: application/json

{
  "username": "ofek_new",
  "email": "ofek_new@test.com"
}

### Delete user (self)
DELETE {{baseUrl}}/users/<userId>
Authorization: Bearer <accessToken>